<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>def</string>
	</array>
	<key>name</key>
	<string>AhaDef</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(ONCHOICE|ONBLUR|PROMPT)\b</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.def</string>
	<key>uuid</key>
	<string>E012E100-B915-11E6-B576-E094675966E4</string>
</dict>
</plist>
