<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>test</string>
	</array>
	<key>name</key>
	<string>JustTest</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>fuck</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.test</string>
	<key>uuid</key>
	<string>CD3C00DE-B902-11E6-BD2B-E094675966E4</string>
</dict>
</plist>
